import { User, Task } from "../../models/definitions";

// Users
export const mockUsers: User[] = [
  { id: 'user1', name: 'Alice' },
  { id: 'user2', name: 'Bob' },
  { id: 'user3', name: 'Charlie' },
];

// Tasks
export const mockTasks: Task[] = [
  {
    id: 'task1',
    title: 'Learn Next.js',
    description: 'Complete the Next.js tutorial',
    ownerId: 'user1',
    subtasksId: [],
    completionStatus: 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'task2',
    title: 'Learn TypeScript',
    description: 'Go through TypeScript documentation',
    ownerId: 'user2',
    subtasksId: ['subtask2-1', 'subtask2-2'],
    completionStatus: 'inprogress',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'subtask2-1',
    title: 'Basics of TypeScript',
    description: 'Learn the basics of TypeScript',
    ownerId: 'user2',
    subtasksId: [],
    completionStatus: 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'subtask2-2',
    title: 'Advanced TypeScript',
    description: 'Learn advanced concepts in TypeScript',
    ownerId: 'user2',
    subtasksId: ['subtask2-2-1', 'subtask2-2-2'],
    completionStatus: 'inprogress',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'subtask2-2-1',
    title: 'Generics in TypeScript',
    description: 'Understand and use generics in TypeScript',
    ownerId: 'user2',
    subtasksId: [],
    completionStatus: 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'subtask2-2-2',
    title: 'Decorators in TypeScript',
    description: 'Learn about decorators in TypeScript',
    ownerId: 'user2',
    subtasksId: [],
    completionStatus: 'inprogress',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task3',
    title: 'Build a Todo App',
    description: 'Use Next.js and TypeScript to build a Todo app',
    ownerId: 'user3',
    subtasksId: ['subtask3-1', 'subtask3-2', 'subtask3-3'],
    completionStatus: 'backlog',
    createdAt: new Date().toISOString(),
    blockedByTasksId: ['subtask3-2'],
  },
  {
    id: 'subtask3-1',
    title: 'Setup Project',
    description: 'Initialize the project with Next.js and TypeScript',
    ownerId: 'user3',
    subtasksId: ['subtask3-1-1'],
    completionStatus: 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'subtask3-1-1',
    title: 'Install Dependencies',
    description: 'Install necessary dependencies for the project',
    ownerId: 'user3',
    subtasksId: [],
    completionStatus: 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'subtask3-2',
    title: 'Create Components',
    description: 'Create necessary components for the Todo app',
    ownerId: 'user3',
    subtasksId: ['subtask3-2-1'],
    completionStatus: 'inprogress',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'subtask3-2-1',
    title: 'Header Component',
    description: 'Create the header component',
    ownerId: 'user3',
    subtasksId: [],
    completionStatus: 'completed',
    createdAt: new Date().toISOString(),
    completedAt: new Date().toISOString(),
  },
  {
    id: 'subtask3-3',
    title: 'Implement State Management',
    description: 'Implement state management for the Todo app',
    ownerId: 'user3',
    subtasksId: [],
    completionStatus: 'backlog',
    createdAt: new Date().toISOString(),
    blockedByTasksId: ['subtask3-2'],
  },
];
